### ISSUE TITLE
mongodb 为什么配置到非本地时会报错呢？

### ISSUE THREAD

**Issue by zteBill** [houko/SpringBootUnity#4]
Description:

Cannot determine embedded database driver class for database type NONE

Action:

If you want an embedded database please put a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need to active it (no profiles are currently active).

**Comment by xiaomoinfo** [comment]
2017.1版本己修复，不好意思。久等

**Comment by zteBill** [comment]
我试了一下 的确可以启动了，请问是哪里配置的问题呢？ 因为我自己写demo测试好像是会报这个错误，一直没搞明白原因是啥，请教一下，谢谢 @xiaomoinfo

**Comment by xiaomoinfo** [comment]
1.5.6版本的改动，如果你没配置数据库信息会报错。他报错的意思是 因为你没有配置数据库信息，程序启动的时候无法决定如何去连接。 

你如果想忽略这个错误，可以在 你的启动函数里 加个这个注解 
@EnableAutoConfiguration(exclude={DataSourceAutoConfiguration.class,HibernateJpaAutoConfiguration.class})

**Comment by xiaomoinfo** [comment]
![f bdd h b0l re2ju i7d](https://user-images.githubusercontent.com/12625278/30235942-7fc52412-9542-11e7-983b-014ec222858f.png)
