### ISSUE TITLE
website 登录无法跳转到登录页面

### ISSUE THREAD

**Issue by ljmomo** [houko/SpringBootUnity#8]
http://localhost:8080/user/toLogin
    直接输出  login

**Comment by xiaomoinfo** [comment]
![qjai pac21 qfl rf f iy9](https://user-images.githubusercontent.com/12625278/30235743-c4ace26c-953e-11e7-93da-391bd1d8848d.png)
![22 ajajlq 6zdyn th2 d 3](https://user-images.githubusercontent.com/12625278/30235745-c4df43f6-953e-11e7-8e04-076d35c96558.png)
![45 ifr mgfme8zv r aeg](https://user-images.githubusercontent.com/12625278/30235744-c4da793e-953e-11e7-9733-ce6ef609d814.png)


bug己修复，多谢指正 @ljmomo

**Comment by xiaomoinfo** [comment]
![image](https://user-images.githubusercontent.com/12625278/30235757-fb99f828-953e-11e7-8e81-e4be2c7382e1.png)
![7 hrzx 7 o egbq_7qxys0](https://user-images.githubusercontent.com/12625278/30235758-fd01fb20-953e-11e7-8afc-f46f0e584bb5.png)

登录之后是这个样子， 点击用户名会退出登录

**Comment by xiaomoinfo** [comment]
![ofvr32jv h26s9 5 0vjvk](https://user-images.githubusercontent.com/12625278/30235853-c43382ee-9540-11e7-842b-05630e2be39e.png)

登录之后是这样子的，点击用户名会退出登录。


注意：   项目启动之前，先在 application.properties 里面的邮箱配置一下
